robots:
    - name: "Robot 201"
      robot_ip: "10.10.10.201"
      server_ip: "10.10.10.210"
      robot_port: 1234
      gripper_port: 1235
    - name: "Robot 202"
      robot_ip: "10.10.10.202" 
      server_ip: "10.10.10.210" 
      robot_port: 4321 
      gripper_port: 4322
